final/urls.py
from django.urls import path
from . import views

# url that is linked to specified files
urlpatterns = [
    path('', views.home, name='home'),
    path('s/', views.search, name='search'),
    path('menu/', views.menu, name='menu'),
    path('order/', views.order, name='order'),
    path('orders/', views.order_2, name='order_2'),
    path('checkout/', views.checkout, name='checkout'),
    path('menu/<slug>/', views.food, name='food'),
    path('order/<slug>/', views.update_cart, name='update_cart'),
    path('contact/us/', views.contact, name='contact'),
    path('about/us/', views.about, name='about'),
    path('accounts/logout/', views.logout_view, name='auth_logout'),
    path('accounts/login/', views.login_view, name='auth_login'),
    path('accounts/register/', views.registration_view, name='auth_register'),
    path('accounts/activate/<activation_key>/', views.activation_view, name='activation_view'),
    path('checkout/completed/', views.message_success, name='message_success'),
]

final_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


# url that links to final and admin
urlpatterns = [
    path('', include('final.urls')),
    path('admin/', admin.site.urls),
] 

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

final/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from django.conf import settings
from django.core.mail import send_mail
from django.template.loader import render_to_string
from decimal import Decimal
import stripe

# Create your models here.

# Adding new product details in admin
class Product(models.Model):
    # Character field is required to have a maximum length
    title = models.CharField(max_length = 120)
    # Field not required (text field)
    description = models.TextField(null = True, blank = True)
    # Decimal field needs to have the decimal places and maximum digits
    price = models.DecimalField(decimal_places = 3, max_digits = 100)
    # Field not required (decimal field)
    sale_price = models.DecimalField(decimal_places = 3, max_digits = 100, null = True, blank = True)
    # Identifier for a product --> unique slug
    slug = models.SlugField(unique = True)
    # First added to the database (date time field)
    timestamp = models.DateTimeField(auto_now_add = True, auto_now = False)
    # Most recently change in database (date time field)
    updated = models.DateTimeField(auto_now_add = False, auto_now = True)
    # The product details by default will show (boolean --> True/False)
    active = models.BooleanField(default = True)

    def __unicode__(self):
        return str(self.title)

    # Unique title and slug
    class Meta:
        unique_together = ('title', 'slug') 

    def get_price(self):
        return self.price

    def get_absolute_url(self):
        return reverse("food", kwargs = {"slug": self.slug })

# Adding new product images in admin
class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    # Upload image for a product
    image = models.ImageField(upload_to = 'products/images/')
    # The product image will not show by default in featured and thumbnail (boolean --> True/False)
    featured = models.BooleanField(default = False)
    thumbnail = models.BooleanField(default = False)
    # The product image by default will show (boolean --> True/False)
    active = models.BooleanField(default = True)
    # Most recently change in database (date time field)
    updated = models.DateTimeField(auto_now_add = False, auto_now = True)

    def __unicode__(self):
        return self.product.title

# Cart item feature in admin
class CartItem(models.Model):
    cart = models.ForeignKey('Cart', null= True, blank = True, on_delete = models.CASCADE)
    # cart foreign key
    product = models.ForeignKey(Product, on_delete = models.CASCADE)
    quantity = models.IntegerField(default = 1)
    # First added to the database (date time field)
    timestamp = models.DateTimeField(auto_now_add = True, auto_now = False)
    # Most recently change in database (date time field)
    updated = models.DateTimeField(auto_now_add = False, auto_now = True)

    def __unicode__(self):
        try:
            return str(self.cart.id)
        except:
            return self.product.title

# Cart features in admin
class Cart(models.Model):
    total = models.DecimalField(decimal_places = 3, max_digits = 100, default = 0.000)
    # First added to the database (date time field)
    timestamp = models.DateTimeField(auto_now_add = True, auto_now = False)
    # Most recently change in database (date time field)
    updated = models.DateTimeField(auto_now_add = False, auto_now = True)
    # The product image by default will show (boolean --> True/False)
    active = models.BooleanField(default = True)

    def __unicode__(self):
        return "Cart id: %s" %(self.id)

# Status types
STATUS_CHOICES = (
    ("Started", "Started"),
    ("Abandoned", "Abandoned"),
    ("Finished", "Finished"),
)

try:
    tax_rate = settings.DEFAULT_TAX_RATE
except Exception as e:
    raise NotImplementedError(str(e))

# Checkout features in admin
class Checkout(models.Model):
    user = models.ForeignKey(User, blank = True, null = True, on_delete = models.CASCADE)
    cart = models.ForeignKey(Cart, on_delete = models.CASCADE)
    # Default choice as start
    status = models.CharField(max_length = 120, choices = STATUS_CHOICES, default = "Started")
    # Address
    address = models.ForeignKey("UserAddress", blank = True, null = True, on_delete = models.CASCADE)
    sub_total = models.DecimalField(default = 0.000, max_digits = 1000, decimal_places = 3)
    tax_total = models.DecimalField(default = 0.000, max_digits = 1000, decimal_places = 3)
    final_total = models.DecimalField(default = 0.000, max_digits = 1000, decimal_places = 3)
    # Unique checkout id
    checkout_id = models.CharField(max_length = 120, default = 'ABC', unique = True)
    timestamp = models.DateTimeField(auto_now_add = True, auto_now = False)
    updated = models.DateTimeField(auto_now_add = False, auto_now = True)

    def __unicode__(self):
        return self.checkout_id

    def get_final_amount(self):
        # Get checkout products
        instance = Checkout.objects.get(id = self.id)
        three_places = Decimal(1000) 
        instance.tax_total = Decimal(Decimal("%s"%(tax_rate)) * Decimal(self.sub_total)).quantize(three_places)
        instance.final_total = Decimal(self.sub_total) + Decimal(instance.tax_total)
        instance.save()
        return instance.final_total

# Userstripe features in admin
class UserStripe(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
    stripe_id = models.CharField(max_length = 120, null = True, blank = True)

    def __unicode__(self):
        return str(self.stripe_id)


# User address features in admin
class UserAddress(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
    address = models.CharField(max_length = 120)
    address2 = models.CharField(max_length = 120, null = True, blank = True)
    city = models.CharField(max_length = 120)
    phone_number = models.CharField(max_length = 120)
    timestamp = models.DateTimeField(auto_now_add = True, auto_now = False)
    updated = models.DateTimeField(auto_now_add = False, auto_now = True)

    def __unicode__(self):
        return str(self.user.username)

    # get the address and city
    def get_address(self):
        return "%s, %s" %(self.address, self.city)


# Email Confirmation features in admin
class EmailConfirmed(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
    activation_key = models.CharField(max_length = 200, null = True, blank = True)
    confirmed = models.BooleanField(default = False)

    def __unicode__(self):
        return str(self.confirmed)

    def activate_user_email(self):
        activation_url = "%s%s" %(settings.SITE_URL, reverse("activation_view", args = [self.activation_key]))
        context = {
            "activation_key" : self.activation_key,
            "activation_url" : activation_url,
            "user" : self.user.username,
        }
        message = render_to_string("activation_message.txt", context)
        subject = "Activate your Email"
        self.email_user(subject, message, settings.DEFAULT_FROM_EMAIL)

    def email_user(self, subject, message, from_email = None, **kwargs):
        send_mail(subject, message, from_email, [self.user.email], kwargs)


    

final/forms.py
from django import forms
from django.contrib.auth import get_user_model
from .models import UserAddress

User = get_user_model()

# Address form feature
class UserAddressForm(forms.ModelForm):
    class Meta:
        model = UserAddress
        fields = ["address", 
                "address2",
                "city", 
                "phone_number",]

# Login an account (the account should exist)
class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget = forms.PasswordInput())

    # Check username
    def clean_username(self):
        username = self.cleaned_data.get("username")
        try:
            user = User.objects.get(username = username)
        except User.DoesNotExist:
            raise forms.ValidationError("Are you sure you are registered? We cannot find this user.")
        return username
    
    # Check password
    def clean_password(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        try:
            user = User.objects.get(username = username)
        except:
            user = None
        
        if user is not None and not user.check_password(password):
            raise forms.ValidationError("Invalid Password")
        elif user is None:
            pass
        else:
            return password

# Register an account
class RegistrationForm(forms.ModelForm):
    email = forms.EmailField(label = "Your Email")
    password1 = forms.CharField(label = "Password", \
                    widget = forms.PasswordInput())
    password2 = forms.CharField(label = "Password Confirmation", \
                    widget = forms.PasswordInput())

    class Meta:
        model = User
        fields = ["username", "email"]

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords do not match")
        return password2

    def clean_email(self):
        email = self.cleaned_data.get("email")
        user_count = User.objects.filter(email = email).count()
        if user_count > 0:
            raise forms.ValidationError("This email has aready been registered. Please check and try again.") 
        return email

    def save(self, commit = True):
        user = super(RegistrationForm, self).save(commit = False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

final/templates/about.html
{% extends "base.html" %}

{% block content %}
<h1>About Us</h1>
{% endblock content %}

final/templates/activation_complete.html
{% extends base.html %}
{% block content %}
    <h1>{{page_message}}</h1>
{% endblock content %}

final/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <style>
        h1{text-align:center}
        h2{text-align:center; padding: 40px;}
        .nav > .div{display:flex;justify-content: space-between;padding: 38px;}
        .navbar-brand{  font-family: 'Lato', sans-serif;color:black!important;font-size: 23px!important; font-weight: bold}
        .nav-item{color:black; font-size:13px; text-transform: uppercase}
        .active-nav-link a{color: black !important; font-weight: bold!important}
        .nav-link-wrapper a {color: #8a8a8a;text-decoration: none;transition: color 0.5s; font-weight: 400;}
        .nav-link-wrapper a:hover {color: black; font-weight: 400;}
        .thumbnail{margin-top: 5px;}
        .wrapper{max-width: 400px; width: 100%; height: 97%; background: #c8ae7e; padding: 30px, 45px; position: absolute; top: 70%; left: 50%; transform: translate(-50%, -50%); border-radius:20px}
        .wrapper .font{color: #ffffff;}
        .background_img_thumb{width:220px; height:200px; background-image:url("{% static 'img/placeholder.svg' %}"); background-size:cover; background-repeat:no-repeat; background-position:center}
        .img-responsive{width: 400px; height: 400px; padding-top: 10px; padding-right: 40px ; padding-left: 0px }
    </style>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Eightery</title>


    <link href='https://fonts.googleapis.com/css?family=Lato:100' rel='stylesheet' type='text/css'>
    <link rel = "stylesheet" href = '{% static "css/bootstrap-theme.min.css" %}' />
    <link rel = "stylesheet" href = '{% static "css/bootstrap.min.css" %}' />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script type="text/javascript" src="https://js.stripe.com/v3/"></script>
    <script src="https://polyfill.io/v3/polyfill.min.js?version=3.52.1&features=fetch"></script>
</head>
<body>
    {% include 'navbar.html' %}
    {% block jumbotron %}
    {% endblock jumbotron%}
    <div class = "container">
        {% block content %}
        {% endblock content %}
    </div>
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
        <script src='http://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js?ver=1.4.2'></script>
      
        {% block jquery %}
        {% endblock jquery %}


</body>
</html>

final/templates/checkout.html
{% extends 'base.html'%}

{% block jquery %}
<script>
    stripe.setPublishableKey('{{ stripe_pub }}')
  var form = document.getElementById('payment-form');
  
  form.addEventListener('submit', function(event) {
    event.preventDefault();
  
    stripe.createSource(card, user).then(function(result) {
      if (result.error) {
        // Inform the user if there was an error
        var errorElement = document.getElementById('card-errors');
        errorElement.textContent = result.error.message;
      } else {
        // Send the source to your server
        stripeSourceHandler(result.source);
      }
    });
  });

  function stripeSourceHandler(source) {
    // Insert the source ID into the form so it gets submitted to the server
    var form = document.getElementById('payment-form');
    var hiddenInput = document.createElement('input');
    hiddenInput.setAttribute('type', 'hidden');
    hiddenInput.setAttribute('name', 'stripeSource');
    hiddenInput.setAttribute('value', source.id);
    form.appendChild(hiddenInput);
  
    // Submit the form
    form.submit();
  }
</script>
{% endblock jquery %}

{% block content %}
    <h1>Current Total: {{ checkout.get_final_amount }}</h1>
    <!--address form-->
    {% if address_form %}
        <div class = 'col-sm-6 pull-right'>
            <h3>Add new address</h3>
            <form method = "POST" action="" id="payment-form">{% csrf_token %}
            {{ address_form.as_p }}
            <input type="submit" class = "btn btn-outline-secondary" value = "Add Address" />
            </form>
        </div>
    {% endif %}


    <form method="POST" action="" id="payment-form">{% csrf_token %}
        <!--Current Address-->
        {% if current_addresses %}
            <div class = 'col-sm-6'>
                <h3>Saved Address</h3>
                <!--get every address that is added-->
                {% for address in current_addresses %}
                    <input type="radio" name = "saved_address" value="{{ address_id }}"/>{{ address.get_address }} <br/>
                    {% endfor %}
            </div>
        {% endif %}

            <!--Credit card information-->
            <div class = 'col-sm-6'>
                <h3>Credit Info</h3>
                <span class = "payment-errors"></span>
                <div class = "form-row">
                    <label>
                        <!--Card Number-->
                        <span>Card Number</span>
                        <input type="text" size="20" data-stripe = "number" />
                    </label>
                </div>

                <div class = "form-row">
                    <label>
                        <!--CVC-->
                        <span>CVC</span>
                        <input type="text" size="4" data-stripe = "cvc" />
                    </label>
                </div>

                <div class = "form-row">
                    <label>
                        <!--Expiration date-->
                        <span>Expiration (MM/YY)</span>
                        <input type="text" size="4" data-stripe = "exp-month" />
                    </label>
                    <label>
                        <span> / </span>
                        <input type="text" size="4" data-stripe = "exp-year" />
                    </label>
                </div>
                <button type="submit">Submit Payment</button>
            </div>
            
    </form>
        
{% endblock content %}

final/templates/contact.html
{% extends "base.html" %}

{% block content %}
<h1>Contact</h1>
{% endblock content %}

final/templates/form.html
{% extends "base.html" %}

{% block content %}
    <div class = 'col-sm-6 col-sm-offset-3' style = 'margin-top: 50px;'>
        <form method = 'POST' action="">{% csrf_token %}
            {{form.as_p}}
            <input type="submit" value = "{% if submit_btn %}{{submit_btn}}{% else %}Submit{% endif %}" class btn btn-default />
        </form>
    </div>
{% endblock content %}

final/templates/home.html
{% extends "base.html" %}
{% load static %}

{% block jumbotron %}
<div class = "container">
    <!--Carousel-->
    <div class = 'container-fluid' style="margin-top: -19px; margin-bottom: 19px; padding: 0px"></div>
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
          <!--<li data-target="#carouselExampleIndicators" data-slide-to="2"></li>-->
        </ol>
        <div class="carousel-inner" role = "listbox">
          <div class="carousel-item active">
            <img class="img-fluid d-block w-100" src="{% static 'img/egg-tart-wood.jpg' %}" style = "height:585px; width: 100%!important;" alt="Egg tart">
          </div>
          <div class="carousel-item">
            <img class="img-fluid d-block w-100" src="{% static 'img/chocotart.PNG' %}" style = "height: 585px; width: 100%!important;" alt="Chocolate tart">
          </div>
          <!--<div class="carousel-item">
            <img class="d-block w-100" src="..." alt="Third slide">
          </div>-->
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
</div>
{% endblock jumbotron %}

{% block content %}
<h2>Recommendation</h2>
<div class = 'row'>
        <!--product in all the products-->
        {% for product in products %}
            <!--column small 3 and thumbnail-->
            <div class = 'col-sm-3'>
            <div class = "thumbnail">
                <!--if there is a product image-->
                {% if product.productimage_set.all %}
                    <!--item in the product image-->
                    {% for item in product.productimage_set.all %}
                        <!--if item is set featured-->
                        {% if item.featured %}
                          <!--Use the style for the following for the product image-->
                          <a href='{{ product.get_absolute_url }}'>
                          <div style = 
                          "width:220px;
                          height:200px;
                          margin:0 auto;">
                          <div class = 'background_img_thumb' style = "background-image:url('/media/{{ item.image }}');"></div>
                          </div>
                          </a>
                        {% endif %}
                    {% endfor %}
                    
                {% else %}
                    <!--the image will be a placeholder-->
                    <a href='{{ product.get_absolute_url }}'>
                    <img class='img-responsive' src='{% static "img/placeholder.svg" %}'/>
                    </a>
                {% endif %}

            <div class = "caption">
                <a href='{{ product.get_absolute_url }}'><h3>{{ product.title }}</h3></a>
                <p>{{ product.description|truncatewords:15}}</p>
            </div>
        </div>


        </div>
            {% cycle "" "" "" "</div></div><div class = 'row'>" %}
                
        {% endfor %}
</div>

{% endblock content %}

final/templates/login_form.html
{% extends "base.html" %}

{% block content %}
<h2>Login</h2>
<div class = "d-flex justify-content-center">
    <div class = 'col-sm-6 col-sm-offset-3' style = 'margin-top: 0px;'>
        <form method = 'POST' action="">{% csrf_token %}
            {{form.as_p}}
            <input type="submit" value = "{% if submit_btn %}{{submit_btn}}{% else %}Submit{% endif %}" class btn btn-default />
            <p><div>Don't have an account?<a href="{% url 'auth_register' %}">Sign up</a></div></p>
        </form>
    </div>
</div>
{% endblock content %}

final/templates/menu.html
{% extends "base.html" %}
{% load static %}
{% block content %}

<h2>Menu</h2>
<div class = 'row'>
        {% for product in products %}
            <div class = 'col-sm-3'>
            <div class = "thumbnail">
                {% if product.productimage_set.all %}
                    {% for item in product.productimage_set.all %}
                        {% if item.featured %}
                            <a href='{{ product.get_absolute_url }}'>
                            <div style = 
                            "width:220px;
                            height:200px;
                            margin:0 auto;">
                            <div class = 'background_img_thumb' style = "background-image:url('/media/{{ item.image }}');"></div>
                            </div>
                            </a>
                    {% endif %}
                    {% endfor %}
                    
                {% else %}
                    <a href='{{ product.get_absolute_url }}'>
                    <img class='img-responsive' src='{% static "img/placeholder.svg" %}'/>
                    </a>
                {% endif %}

            <div class = "caption">
                <a href='{{ product.get_absolute_url }}'><h3>{{ product.title }}</h3></a>
                <p>{{ product.description|truncatewords:15}}</p>
            </div>
        </div>


        </div>
            {% cycle "" "" "" "</div></div><div class = 'row'>" %}
                
        {% endfor %}
</div>

{% endblock content %}

final/templates/message_success.html
{% extends 'base.html'%}
{% block content %}
<h2><p>Thank you! Your order has been completed.</p></h2>
{% endblock content %}

final/templates/navbar.html
<!-- start of navbar -->
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: ffffff;">
<a class="navbar-brand" href="{% url 'home'%}">Eightery</a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
</button>

<div class="collapse navbar-collapse" id= "navbarNavDropdown">
    <ul class="navbar-nav ml-auto">
        <form class="navbar-form navbar-right" role = "search" action = '/s/'>
            <div class="form-group">
                <input class="form-control form-control-sm mr-3 w-75" type="text" name = 'q' placeholder ="Search Product Title" aria-label="Search">
            </div>
            <i class="fas fa-search" aria-hidden="true"></i>
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
            
        <li class="nav-item">
            <a class="nav-link" href="{% url 'home'%}">Home </a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="{% url 'menu'%}">Menu </a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="{% url 'order'%}">Order </a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="{% url 'contact'%}">Contact Us </a>
        </li>

        <li class="nav-item">
            <a class="nav-link" href="{% url 'about'%}">About Us </a>
        </li>
        {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="#">Account </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auth_logout' %}">Logout </a>
            </li>
        {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auth_login' %}">Login </a>
            </li>
        {% endif %}
    </div>
</nav>
<!-- end of navbar -->

final/templates/order.html
{% extends "base.html" %}
{% block content %}
{% if empty %}
<h1 style = 'text-align:center;'>{{ empty_message }}</h1>

{% else %}
<div class = 'col-sm-8 col-sm-offset-2'>
<table class = 'table'>

<thead>
    <th>Item</th>
    <th>Price</th>
    <th>Qty</th>
    <th></th>
</thead>


    {% for item in cart.cartitem_set.all %}

        <tr>
            <td> {{ item.product.title }}</td>
            <td>{{ item.product.price }}</td>
            <td>{{ item.quantity }}</td>
            <td><a href='{% url "update_cart" item.product.slug %}?qty=0'>Remove</a></tr>
    {% endfor %}

<tfoot>
    <tr>
        <td></td>
        <td></td>
        <td>Total: {{ cart.total }}</td>
    </tr>
</tfoot>
</table>
<hr/>
<a href="{% url 'checkout' %}">Checkout</a>

</div>
{% endif %}
{% endblock content %}

final/templates/results.html
{% extends 'base.html' %}

{% block content %}

<h1>Searched for: {{ query }}</h1>

<table class = 'table'>
    <thead>
        <th></th>
        <th>Product</th>
    </thead>

    <tbody>
        {% for product in products %}
        <tr>
            <td style = "width: 160px; height: 160px">

                {% if product.productimage_set.all %}
                    {% for item in product.productimage_set.all %}
                        {% if item.featured %}
                            <a href='{{ product.get_absolute_url }}'>
                            <div class = 'background_img_thumb' style = "height: 160px; width:160px; background-image:url('/media/{{ item.image }}')"></div>
                            </a>
                        {% endif %}
                    {% endfor %}
                {% else %}
                    <a href='{{ product.get_absolute_url }}'>
                    <div class = 'background_img_thumb' style = "height: 160px; width:160px" ></div>
                    </a>
                {% endif %}
            </td>
            <td>
                <a href='{{ product.get_absolute_url }}'>
                {{ product.title }}</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock content %}

final/templates/user.html
{% extends 'base.html' %}
{% block content %}

{{user.checkout_set.all}}


{% endblock content %}